name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Set up Python 3.12.0
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mysql-connector-python
        pip install pandas

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_PROJECT_KEY: jandersonazevedo_trabalho-manutencao
        SONAR_ORGANIZATION: sistema-de-gestao-de-loja

    # Adicione o trecho abaixo para forçar o uso do Node.js versão 16
    - name: Use Node.js 16
      run: setup-node@v3
      with:
        node-version: '16'
